steps:
# Construye la imagen de Docker
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'gcr.io/$PROJECT_ID/app', '.']

# Sube la imagen a Container Registry
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'gcr.io/$PROJECT_ID/app']

# Despliega la imagen en Cloud Run
- name: 'gcr.io/cloud-builders/gcloud'
  args:
    - 'run'
    - 'deploy'
    - 'app'
    - '--image=gcr.io/$PROJECT_ID/app'
    - '--platform=managed'
    - '--region=europe-west1'  # Ajusta la región según tu preferencia